#!/bin/bash

source ~/.bashrc


rostopic pub /ekf_slam_node/slam_odom_fix sensor_msgs/NavSatFix "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
status: {status: 0, service: 0}
latitude: 42.0
longitude: 12.0
altitude: 300.0
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0" -r 1
